import java.util.ArrayList;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mangqin' at '5/6/16 11:23 AM' with Gradle 2.13
 *
 * @author mangqin, @date 5/6/16 11:23 AM
 */
public class PrimePopulate {
	public static ArrayList<Integer> populate(int n) {
		
		ArrayList<Integer> numbers = new ArrayList<Integer>();
		if (n<=0) {
			return numbers;
		}
		boolean prime = true;
		int num = 3;
		if (num >= 1) {
    		numbers.add(2);
    	}
		for ( int count = 2 ; count <=n ;  ) {
			for ( int j = 2 ; j <= Math.sqrt(num) ; j++ ) {
				if ( num%j == 0 ){
					prime = false;
					break;
				}
			}
			if ( prime ) {
				numbers.add(new Integer(num));
				count++;
			}
			prime=true;
			num++;
		}
		return numbers;
	}        
    
}
